# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02b0009301e239974972de9771bbade17286d700426a894b7181868b6bda1d564cc6e1550b8895301be4414651edfb3f695793a59e7bcc25ada67b3428b58da3

test:
  secret_key_base: 459f1cc1459fa2869e5d1cce80c823e26316e4089a5a3ada392364ead07764ac61012a44975fdebea605cf26a712a20f696009e389183fd62c07bd9710c5e482

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
